name: Deploy to Oxygen

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: .

jobs:
  deploy:
    name: Deploy to Oxygen
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build and Deploy storefront
        run: pnpm run build
